// Export utilities for PDF generation
export const exportToPDF = (content, filename = 'climacrop-report') => {
  // Simple HTML to PDF using browser print
  const printWindow = window.open('', '_blank');
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${filename}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 20px;
            color: #333;
          }
          h1, h2, h3 {
            color: #28a745;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
          }
          th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
          }
          th {
            background-color: #28a745;
            color: white;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
          }
          .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #666;
          }
        </style>
      </head>
      <body>
        ${content}
        <div class="footer">
          <p>Generated by ClimaCrop - AI-Powered Crop Recommendation System</p>
          <p>Date: ${new Date().toLocaleDateString()}</p>
        </div>
      </body>
    </html>
  `);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
  }, 250);
};

export const exportChartAsImage = (chartId, filename = 'chart') => {
  const chartElement = document.getElementById(chartId);
  if (!chartElement) return;

  // Use html2canvas if available, otherwise use print
  if (window.html2canvas) {
    window.html2canvas(chartElement).then(canvas => {
      const link = document.createElement('a');
      link.download = `${filename}.png`;
      link.href = canvas.toDataURL();
      link.click();
    });
  } else {
    // Fallback to print
    exportToPDF(chartElement.innerHTML, filename);
  }
};




